import type { Genre, Priority, PuzzleForm, Puzzle, SortMode, Status, WishlistItem } from './types';

export const GENRES_ALL: Array<Genre | 'Tous'> = ['Tous', 'Paysage', 'Animaux', 'Art', 'Fantaisie', 'Ville'];
export const ADD_GENRES: Genre[] = ['Paysage', 'Animaux', 'Art', 'Fantaisie', 'Ville'];
export const SORT_MODES: SortMode[] = ['Récent', 'Alphabétique', 'Pièces', 'Difficulté'];
export const STATUSES: Status[] = ['À faire', 'En cours', 'Terminé'];
export const PRIORITIES: Priority[] = ['Basse', 'Moyenne', 'Haute'];

export const RAW_COLLECTION: Puzzle[] = [
  {
    id: 'p1',
    name: 'Coucher de soleil sur les Alpes',
    brand: 'Ravensburger',
    genre: 'Paysage',
    pieces: 1000,
    status: 'Terminé',
    rating: 5,
    difficulty: 3,
    date: '12 mars 2026',
    time: '18h30',
    notes: 'Un régal, les dégradés de ciel étaient magnifiques à assembler. À refaire !',
  },
  {
    id: 'p2',
    name: 'Renards dans la neige',
    brand: 'Nathan',
    genre: 'Animaux',
    pieces: 500,
    status: 'Terminé',
    rating: 4,
    difficulty: 2,
    date: '2 février 2026',
    time: '9h15',
    notes: 'Pièces bien découpées, parfait pour une soirée entre amies.',
  },
  {
    id: 'p3',
    name: 'La nuit étoilée revisitée',
    brand: 'Educa',
    genre: 'Art',
    pieces: 1500,
    status: 'En cours',
    rating: 0,
    difficulty: 5,
    date: '—',
    time: '6h40 (en cours)',
    notes: 'Le ciel bleu foncé est un vrai challenge, plein de pièces qui se ressemblent.',
  },
  {
    id: 'p4',
    name: 'Château enchanté',
    brand: 'Clementoni',
    genre: 'Fantaisie',
    pieces: 2000,
    status: 'À faire',
    rating: 0,
    difficulty: 4,
    date: '—',
    time: '—',
    notes: 'Reçu en cadeau, hâte de le commencer après le prochain.',
  },
  {
    id: 'p5',
    name: 'Marché de Venise',
    brand: 'Ravensburger',
    genre: 'Ville',
    pieces: 1000,
    status: 'Terminé',
    rating: 5,
    difficulty: 3,
    date: '28 janvier 2026',
    time: '15h10',
    notes: 'Les couleurs des façades rendent super bien, un des préférés.',
  },
  {
    id: 'p6',
    name: 'Perroquets tropicaux',
    brand: 'Nathan',
    genre: 'Animaux',
    pieces: 300,
    status: 'Terminé',
    rating: 3,
    difficulty: 1,
    date: '5 janvier 2026',
    time: '4h20',
    notes: 'Rapide et coloré, parfait pour se détendre après le boulot.',
  },
  {
    id: 'p7',
    name: 'Vignoble en automne',
    brand: 'Educa',
    genre: 'Paysage',
    pieces: 1000,
    status: 'En cours',
    rating: 0,
    difficulty: 3,
    date: '—',
    time: '3h05 (en cours)',
    notes: 'Beaucoup de teintes orangées proches, ça demande de la patience.',
  },
];

export const RAW_WISHLIST: WishlistItem[] = [
  {
    id: 'w1',
    name: 'Aurores boréales en Islande',
    brand: 'Ravensburger',
    genre: 'Paysage',
    pieces: 2000,
    priority: 'Haute',
    notes: 'Vue dans une boutique, les couleurs sont juste magnifiques.',
  },
  {
    id: 'w2',
    name: 'Chats de Paris',
    brand: 'Nathan',
    genre: 'Animaux',
    pieces: 500,
    priority: 'Moyenne',
    notes: 'Parfait pour une soirée courte entre deux gros puzzles.',
  },
  {
    id: 'w3',
    name: 'Bibliothèque secrète',
    brand: 'Clementoni',
    genre: 'Fantaisie',
    pieces: 1500,
    priority: 'Haute',
    notes: "L'illustration façon conte donne vraiment envie.",
  },
];

export const EMPTY_FORM: PuzzleForm = {
  name: '',
  brand: '',
  genre: ADD_GENRES[0],
  pieces: '',
  status: 'À faire',
  priority: 'Moyenne',
  notes: '',
};
